import {
	ARXIV_PREFIX_TO_FIELD,
	FIELDS_OF_STUDY,
	type FieldOfStudy,
} from "../papers/fields";

// Re-exported for convenience — Semantic Scholar's categories already *are*
// this canonical vocabulary, nothing to map or duplicate.
export { FIELDS_OF_STUDY };

export interface ArxivCategory {
	code: string;
	name: string;
}

export interface ArxivArchive {
	// The literal OAI-PMH set value for this archive — bare categories
	// with no subcodes (e.g. "gr-qc") ARE the archive.
	archive: string;
	label: string;
	categories: ArxivCategory[];
}

export interface ArxivSuperGroup {
	superGroup: string;
	label: string;
	archives: ArxivArchive[];
}

// Full arXiv category taxonomy — 155 codes across 8 top-level groups,
// confirmed live against arxiv.org/category_taxonomy.
export const ARXIV_TAXONOMY: ArxivSuperGroup[] = [
	{
		superGroup: "cs",
		label: "Computer Science",
		archives: [
			{
				archive: "cs",
				label: "Computer Science",
				categories: [
					{ code: "cs.AI", name: "Artificial Intelligence" },
					{ code: "cs.AR", name: "Hardware Architecture" },
					{ code: "cs.CC", name: "Computational Complexity" },
					{ code: "cs.CE", name: "Computational Engineering, Finance, and Science" },
					{ code: "cs.CG", name: "Computational Geometry" },
					{ code: "cs.CL", name: "Computation and Language" },
					{ code: "cs.CR", name: "Cryptography and Security" },
					{ code: "cs.CV", name: "Computer Vision and Pattern Recognition" },
					{ code: "cs.CY", name: "Computers and Society" },
					{ code: "cs.DB", name: "Databases" },
					{ code: "cs.DC", name: "Distributed, Parallel, and Cluster Computing" },
					{ code: "cs.DL", name: "Digital Libraries" },
					{ code: "cs.DM", name: "Discrete Mathematics" },
					{ code: "cs.DS", name: "Data Structures and Algorithms" },
					{ code: "cs.ET", name: "Emerging Technologies" },
					{ code: "cs.FL", name: "Formal Languages and Automata Theory" },
					{ code: "cs.GL", name: "General Literature" },
					{ code: "cs.GR", name: "Graphics" },
					{ code: "cs.GT", name: "Computer Science and Game Theory" },
					{ code: "cs.HC", name: "Human-Computer Interaction" },
					{ code: "cs.IR", name: "Information Retrieval" },
					{ code: "cs.IT", name: "Information Theory" },
					{ code: "cs.LG", name: "Machine Learning" },
					{ code: "cs.LO", name: "Logic in Computer Science" },
					{ code: "cs.MA", name: "Multiagent Systems" },
					{ code: "cs.MM", name: "Multimedia" },
					{ code: "cs.MS", name: "Mathematical Software" },
					{ code: "cs.NA", name: "Numerical Analysis" },
					{ code: "cs.NE", name: "Neural and Evolutionary Computing" },
					{ code: "cs.NI", name: "Networking and Internet Architecture" },
					{ code: "cs.OH", name: "Other Computer Science" },
					{ code: "cs.OS", name: "Operating Systems" },
					{ code: "cs.PF", name: "Performance" },
					{ code: "cs.PL", name: "Programming Languages" },
					{ code: "cs.RO", name: "Robotics" },
					{ code: "cs.SC", name: "Symbolic Computation" },
					{ code: "cs.SD", name: "Sound" },
					{ code: "cs.SE", name: "Software Engineering" },
					{ code: "cs.SI", name: "Social and Information Networks" },
					{ code: "cs.SY", name: "Systems and Control" },
				],
			},
		],
	},
	{
		superGroup: "econ",
		label: "Economics",
		archives: [
			{
				archive: "econ",
				label: "Economics",
				categories: [
					{ code: "econ.EM", name: "Econometrics" },
					{ code: "econ.GN", name: "General Economics" },
					{ code: "econ.TH", name: "Theoretical Economics" },
				],
			},
		],
	},
	{
		superGroup: "eess",
		label: "Electrical Engineering and Systems Science",
		archives: [
			{
				archive: "eess",
				label: "Electrical Engineering and Systems Science",
				categories: [
					{ code: "eess.AS", name: "Audio and Speech Processing" },
					{ code: "eess.IV", name: "Image and Video Processing" },
					{ code: "eess.SP", name: "Signal Processing" },
					{ code: "eess.SY", name: "Systems and Control" },
				],
			},
		],
	},
	{
		superGroup: "math",
		label: "Mathematics",
		archives: [
			{
				archive: "math",
				label: "Mathematics",
				categories: [
					{ code: "math.AC", name: "Commutative Algebra" },
					{ code: "math.AG", name: "Algebraic Geometry" },
					{ code: "math.AP", name: "Analysis of PDEs" },
					{ code: "math.AT", name: "Algebraic Topology" },
					{ code: "math.CA", name: "Classical Analysis and ODEs" },
					{ code: "math.CO", name: "Combinatorics" },
					{ code: "math.CT", name: "Category Theory" },
					{ code: "math.CV", name: "Complex Variables" },
					{ code: "math.DG", name: "Differential Geometry" },
					{ code: "math.DS", name: "Dynamical Systems" },
					{ code: "math.FA", name: "Functional Analysis" },
					{ code: "math.GM", name: "General Mathematics" },
					{ code: "math.GN", name: "General Topology" },
					{ code: "math.GR", name: "Group Theory" },
					{ code: "math.GT", name: "Geometric Topology" },
					{ code: "math.HO", name: "History and Overview" },
					{ code: "math.IT", name: "Information Theory" },
					{ code: "math.KT", name: "K-Theory and Homology" },
					{ code: "math.LO", name: "Logic" },
					{ code: "math.MG", name: "Metric Geometry" },
					{ code: "math.MP", name: "Mathematical Physics" },
					{ code: "math.NA", name: "Numerical Analysis" },
					{ code: "math.NT", name: "Number Theory" },
					{ code: "math.OA", name: "Operator Algebras" },
					{ code: "math.OC", name: "Optimization and Control" },
					{ code: "math.PR", name: "Probability" },
					{ code: "math.QA", name: "Quantum Algebra" },
					{ code: "math.RA", name: "Rings and Algebras" },
					{ code: "math.RT", name: "Representation Theory" },
					{ code: "math.SG", name: "Symplectic Geometry" },
					{ code: "math.SP", name: "Spectral Theory" },
					{ code: "math.ST", name: "Statistics Theory" },
				],
			},
		],
	},
	{
		superGroup: "physics",
		label: "Physics",
		archives: [
			{
				archive: "astro-ph",
				label: "Astrophysics",
				categories: [
					{ code: "astro-ph.CO", name: "Cosmology and Nongalactic Astrophysics" },
					{ code: "astro-ph.EP", name: "Earth and Planetary Astrophysics" },
					{ code: "astro-ph.GA", name: "Astrophysics of Galaxies" },
					{ code: "astro-ph.HE", name: "High Energy Astrophysical Phenomena" },
					{ code: "astro-ph.IM", name: "Instrumentation and Methods for Astrophysics" },
					{ code: "astro-ph.SR", name: "Solar and Stellar Astrophysics" },
				],
			},
			{
				archive: "cond-mat",
				label: "Condensed Matter",
				categories: [
					{ code: "cond-mat.dis-nn", name: "Disordered Systems and Neural Networks" },
					{ code: "cond-mat.mes-hall", name: "Mesoscale and Nanoscale Physics" },
					{ code: "cond-mat.mtrl-sci", name: "Materials Science" },
					{ code: "cond-mat.other", name: "Other Condensed Matter" },
					{ code: "cond-mat.quant-gas", name: "Quantum Gases" },
					{ code: "cond-mat.soft", name: "Soft Condensed Matter" },
					{ code: "cond-mat.stat-mech", name: "Statistical Mechanics" },
					{ code: "cond-mat.str-el", name: "Strongly Correlated Electrons" },
					{ code: "cond-mat.supr-con", name: "Superconductivity" },
				],
			},
			{
				archive: "gr-qc",
				label: "General Relativity and Quantum Cosmology",
				categories: [],
			},
			{
				archive: "hep-ex",
				label: "High Energy Physics - Experiment",
				categories: [],
			},
			{
				archive: "hep-lat",
				label: "High Energy Physics - Lattice",
				categories: [],
			},
			{
				archive: "hep-ph",
				label: "High Energy Physics - Phenomenology",
				categories: [],
			},
			{
				archive: "hep-th",
				label: "High Energy Physics - Theory",
				categories: [],
			},
			{
				archive: "math-ph",
				label: "Mathematical Physics",
				categories: [],
			},
			{
				archive: "nlin",
				label: "Nonlinear Sciences",
				categories: [
					{ code: "nlin.AO", name: "Adaptation and Self-Organizing Systems" },
					{ code: "nlin.CD", name: "Chaotic Dynamics" },
					{ code: "nlin.CG", name: "Cellular Automata and Lattice Gases" },
					{ code: "nlin.PS", name: "Pattern Formation and Solitons" },
					{ code: "nlin.SI", name: "Exactly Solvable and Integrable Systems" },
				],
			},
			{
				archive: "nucl-ex",
				label: "Nuclear Experiment",
				categories: [],
			},
			{
				archive: "nucl-th",
				label: "Nuclear Theory",
				categories: [],
			},
			{
				archive: "physics",
				label: "Physics (General)",
				categories: [
					{ code: "physics.acc-ph", name: "Accelerator Physics" },
					{ code: "physics.ao-ph", name: "Atmospheric and Oceanic Physics" },
					{ code: "physics.app-ph", name: "Applied Physics" },
					{ code: "physics.atm-clus", name: "Atomic and Molecular Clusters" },
					{ code: "physics.atom-ph", name: "Atomic Physics" },
					{ code: "physics.bio-ph", name: "Biological Physics" },
					{ code: "physics.chem-ph", name: "Chemical Physics" },
					{ code: "physics.class-ph", name: "Classical Physics" },
					{ code: "physics.comp-ph", name: "Computational Physics" },
					{ code: "physics.data-an", name: "Data Analysis, Statistics and Probability" },
					{ code: "physics.ed-ph", name: "Physics Education" },
					{ code: "physics.flu-dyn", name: "Fluid Dynamics" },
					{ code: "physics.gen-ph", name: "General Physics" },
					{ code: "physics.geo-ph", name: "Geophysics" },
					{ code: "physics.hist-ph", name: "History and Philosophy of Physics" },
					{ code: "physics.ins-det", name: "Instrumentation and Detectors" },
					{ code: "physics.med-ph", name: "Medical Physics" },
					{ code: "physics.optics", name: "Optics" },
					{ code: "physics.plasm-ph", name: "Plasma Physics" },
					{ code: "physics.pop-ph", name: "Popular Physics" },
					{ code: "physics.soc-ph", name: "Physics and Society" },
					{ code: "physics.space-ph", name: "Space Physics" },
				],
			},
			{
				archive: "quant-ph",
				label: "Quantum Physics",
				categories: [],
			},
		],
	},
	{
		superGroup: "q-bio",
		label: "Quantitative Biology",
		archives: [
			{
				archive: "q-bio",
				label: "Quantitative Biology",
				categories: [
					{ code: "q-bio.BM", name: "Biomolecules" },
					{ code: "q-bio.CB", name: "Cell Behavior" },
					{ code: "q-bio.GN", name: "Genomics" },
					{ code: "q-bio.MN", name: "Molecular Networks" },
					{ code: "q-bio.NC", name: "Neurons and Cognition" },
					{ code: "q-bio.OT", name: "Other Quantitative Biology" },
					{ code: "q-bio.PE", name: "Populations and Evolution" },
					{ code: "q-bio.QM", name: "Quantitative Methods" },
					{ code: "q-bio.SC", name: "Subcellular Processes" },
					{ code: "q-bio.TO", name: "Tissues and Organs" },
				],
			},
		],
	},
	{
		superGroup: "q-fin",
		label: "Quantitative Finance",
		archives: [
			{
				archive: "q-fin",
				label: "Quantitative Finance",
				categories: [
					{ code: "q-fin.CP", name: "Computational Finance" },
					{ code: "q-fin.EC", name: "Economics" },
					{ code: "q-fin.GN", name: "General Finance" },
					{ code: "q-fin.MF", name: "Mathematical Finance" },
					{ code: "q-fin.PM", name: "Portfolio Management" },
					{ code: "q-fin.PR", name: "Pricing of Securities" },
					{ code: "q-fin.RM", name: "Risk Management" },
					{ code: "q-fin.ST", name: "Statistical Finance" },
					{ code: "q-fin.TR", name: "Trading and Market Microstructure" },
				],
			},
		],
	},
	{
		superGroup: "stat",
		label: "Statistics",
		archives: [
			{
				archive: "stat",
				label: "Statistics",
				categories: [
					{ code: "stat.AP", name: "Applications" },
					{ code: "stat.CO", name: "Computation" },
					{ code: "stat.ME", name: "Methodology" },
					{ code: "stat.ML", name: "Machine Learning" },
					{ code: "stat.OT", name: "Other Statistics" },
					{ code: "stat.TH", name: "Statistics Theory" },
				],
			},
		],
	},
];
export interface DoajLccTerm {
	label: string;
	// Opaque token required by the OAI-PMH `set=` parameter — not
	// derivable from the label, must be captured alongside it.
	setSpec: string;
}

// All 538 DOAJ LCC subject terms, confirmed live against
// doaj.org/oai?verb=ListSets (the journal-feed endpoint — ListSets is
// shared across both feeds).
export const DOAJ_LCC_TERMS: DoajLccTerm[] = [
	{ label: "1789-", setSpec: "TENDOjE3ODkt" },
	{ label: "Academies and learned societies", setSpec: "TENDOkFjYWRlbWllcyBhbmQgbGVhcm5lZCBzb2NpZXRpZXM~" },
	{ label: "Accounting. Bookkeeping", setSpec: "TENDOkFjY291bnRpbmcuIEJvb2trZWVwaW5n" },
	{ label: "Acoustics in engineering. Acoustical engineering", setSpec: "TENDOkFjb3VzdGljcyBpbiBlbmdpbmVlcmluZy4gQWNvdXN0aWNhbCBlbmdpbmVlcmluZw~~" },
	{ label: "Acoustics. Sound", setSpec: "TENDOkFjb3VzdGljcy4gU291bmQ~" },
	{ label: "Advertising", setSpec: "TENDOkFkdmVydGlzaW5n" },
	{ label: "Aesthetics", setSpec: "TENDOkFlc3RoZXRpY3M~" },
	{ label: "Aesthetics of cities. City planning and beautifying", setSpec: "TENDOkFlc3RoZXRpY3Mgb2YgY2l0aWVzLiBDaXR5IHBsYW5uaW5nIGFuZCBiZWF1dGlmeWluZw~~" },
	{ label: "African languages and literature", setSpec: "TENDOkFmcmljYW4gbGFuZ3VhZ2VzIGFuZCBsaXRlcmF0dXJl" },
	{ label: "Agricultural industries", setSpec: "TENDOkFncmljdWx0dXJhbCBpbmR1c3RyaWVz" },
	{ label: "Agriculture", setSpec: "TENDOkFncmljdWx0dXJl" },
	{ label: "Agriculture (General)", setSpec: "TENDOkFncmljdWx0dXJlIChHZW5lcmFsKQ~~" },
	{ label: "America", setSpec: "TENDOkFtZXJpY2E~" },
	{ label: "American literature", setSpec: "TENDOkFtZXJpY2FuIGxpdGVyYXR1cmU~" },
	{ label: "Analysis", setSpec: "TENDOkFuYWx5c2lz" },
	{ label: "Analytic mechanics", setSpec: "TENDOkFuYWx5dGljIG1lY2hhbmljcw~~" },
	{ label: "Analytical chemistry", setSpec: "TENDOkFuYWx5dGljYWwgY2hlbWlzdHJ5" },
	{ label: "Ancient history", setSpec: "TENDOkFuY2llbnQgaGlzdG9yeQ~~" },
	{ label: "Anesthesiology", setSpec: "TENDOkFuZXN0aGVzaW9sb2d5" },
	{ label: "Animal biochemistry", setSpec: "TENDOkFuaW1hbCBiaW9jaGVtaXN0cnk~" },
	{ label: "Animal culture", setSpec: "TENDOkFuaW1hbCBjdWx0dXJl" },
	{ label: "Anthropology", setSpec: "TENDOkFudGhyb3BvbG9neQ~~" },
	{ label: "Applications of electric power", setSpec: "TENDOkFwcGxpY2F0aW9ucyBvZiBlbGVjdHJpYyBwb3dlcg~~" },
	{ label: "Applied mathematics. Quantitative methods", setSpec: "TENDOkFwcGxpZWQgbWF0aGVtYXRpY3MuIFF1YW50aXRhdGl2ZSBtZXRob2Rz" },
	{ label: "Applied optics. Photonics", setSpec: "TENDOkFwcGxpZWQgb3B0aWNzLiBQaG90b25pY3M~" },
	{ label: "Aquaculture. Fisheries. Angling", setSpec: "TENDOkFxdWFjdWx0dXJlLiBGaXNoZXJpZXMuIEFuZ2xpbmc~" },
	{ label: "Archaeology", setSpec: "TENDOkFyY2hhZW9sb2d5" },
	{ label: "Architectural drawing and design", setSpec: "TENDOkFyY2hpdGVjdHVyYWwgZHJhd2luZyBhbmQgZGVzaWdu" },
	{ label: "Architectural engineering. Structural engineering of buildings", setSpec: "TENDOkFyY2hpdGVjdHVyYWwgZW5naW5lZXJpbmcuIFN0cnVjdHVyYWwgZW5naW5lZXJpbmcgb2YgYnVpbGRpbmdz" },
	{ label: "Architecture", setSpec: "TENDOkFyY2hpdGVjdHVyZQ~~" },
	{ label: "Arctic medicine. Tropical medicine", setSpec: "TENDOkFyY3RpYyBtZWRpY2luZS4gVHJvcGljYWwgbWVkaWNpbmU~" },
	{ label: "Arts in general", setSpec: "TENDOkFydHMgaW4gZ2VuZXJhbA~~" },
	{ label: "Asia and Eurasia, Africa, Pacific Area, and Antarctica", setSpec: "TENDOkFzaWEgYW5kIEV1cmFzaWEsIEFmcmljYSwgUGFjaWZpYyBBcmVhLCBhbmQgQW50YXJjdGljYQ~~" },
	{ label: "Asian. Oriental", setSpec: "TENDOkFzaWFuLiBPcmllbnRhbA~~" },
	{ label: "Astronomy", setSpec: "TENDOkFzdHJvbm9teQ~~" },
	{ label: "Astrophysics", setSpec: "TENDOkFzdHJvcGh5c2ljcw~~" },
	{ label: "Atomic physics. Constitution and properties of matter", setSpec: "TENDOkF0b21pYyBwaHlzaWNzLiBDb25zdGl0dXRpb24gYW5kIHByb3BlcnRpZXMgb2YgbWF0dGVy" },
	{ label: "Austria. Austro-Hungarian Empire", setSpec: "TENDOkF1c3RyaWEuIEF1c3Ryby1IdW5nYXJpYW4gRW1waXJl" },
	{ label: "Automation", setSpec: "TENDOkF1dG9tYXRpb24~" },
	{ label: "Auxiliary sciences of history", setSpec: "TENDOkF1eGlsaWFyeSBzY2llbmNlcyBvZiBoaXN0b3J5" },
	{ label: "Balance of trade", setSpec: "TENDOkJhbGFuY2Ugb2YgdHJhZGU~" },
	{ label: "Banking", setSpec: "TENDOkJhbmtpbmc~" },
	{ label: "Bibliography", setSpec: "TENDOkJpYmxpb2dyYXBoeQ~~" },
	{ label: "Bibliography. Library science. Information resources", setSpec: "TENDOkJpYmxpb2dyYXBoeS4gTGlicmFyeSBzY2llbmNlLiBJbmZvcm1hdGlvbiByZXNvdXJjZXM~" },
	{ label: "Biochemistry", setSpec: "TENDOkJpb2NoZW1pc3RyeQ~~" },
	{ label: "Biography", setSpec: "TENDOkJpb2dyYXBoeQ~~" },
	{ label: "Biology (General)", setSpec: "TENDOkJpb2xvZ3kgKEdlbmVyYWwp" },
	{ label: "Biotechnology", setSpec: "TENDOkJpb3RlY2hub2xvZ3k~" },
	{ label: "Botany", setSpec: "TENDOkJvdGFueQ~~" },
	{ label: "Bridge engineering", setSpec: "TENDOkJyaWRnZSBlbmdpbmVlcmluZw~~" },
	{ label: "Buddhism", setSpec: "TENDOkJ1ZGRoaXNt" },
	{ label: "Building construction", setSpec: "TENDOkJ1aWxkaW5nIGNvbnN0cnVjdGlvbg~~" },
	{ label: "Business", setSpec: "TENDOkJ1c2luZXNz" },
	{ label: "Business communication. Including business report writing, business correspondence", setSpec: "TENDOkJ1c2luZXNzIGNvbW11bmljYXRpb24uIEluY2x1ZGluZyBidXNpbmVzcyByZXBvcnQgd3JpdGluZywgYnVzaW5lc3MgY29ycmVzcG9uZGVuY2U~" },
	{ label: "Business ethics", setSpec: "TENDOkJ1c2luZXNzIGV0aGljcw~~" },
	{ label: "Business mathematics. Commercial arithmetic. Including tables, etc.", setSpec: "TENDOkJ1c2luZXNzIG1hdGhlbWF0aWNzLiBDb21tZXJjaWFsIGFyaXRobWV0aWMuIEluY2x1ZGluZyB0YWJsZXMsIGV0Yy4~" },
	{ label: "Business records management", setSpec: "TENDOkJ1c2luZXNzIHJlY29yZHMgbWFuYWdlbWVudA~~" },
	{ label: "By period", setSpec: "TENDOkJ5IHBlcmlvZA~~" },
	{ label: "By religion", setSpec: "TENDOkJ5IHJlbGlnaW9u" },
	{ label: "Cadastral mapping", setSpec: "TENDOkNhZGFzdHJhbCBtYXBwaW5n" },
	{ label: "Canals and inland navigation. Waterways", setSpec: "TENDOkNhbmFscyBhbmQgaW5sYW5kIG5hdmlnYXRpb24uIFdhdGVyd2F5cw~~" },
	{ label: "Capital. Capital investments", setSpec: "TENDOkNhcGl0YWwuIENhcGl0YWwgaW52ZXN0bWVudHM~" },
	{ label: "Cartography", setSpec: "TENDOkNhcnRvZ3JhcGh5" },
	{ label: "Cattle", setSpec: "TENDOkNhdHRsZQ~~" },
	{ label: "Cellular telephone services industry. Wireless telephone industry", setSpec: "TENDOkNlbGx1bGFyIHRlbGVwaG9uZSBzZXJ2aWNlcyBpbmR1c3RyeS4gV2lyZWxlc3MgdGVsZXBob25lIGluZHVzdHJ5" },
	{ label: "Cement industries", setSpec: "TENDOkNlbWVudCBpbmR1c3RyaWVz" },
	{ label: "Chemical engineering", setSpec: "TENDOkNoZW1pY2FsIGVuZ2luZWVyaW5n" },
	{ label: "Chemical industries", setSpec: "TENDOkNoZW1pY2FsIGluZHVzdHJpZXM~" },
	{ label: "Chemical technology", setSpec: "TENDOkNoZW1pY2FsIHRlY2hub2xvZ3k~" },
	{ label: "Chemicals: Manufacture, use, etc.", setSpec: "TENDOkNoZW1pY2FsczogTWFudWZhY3R1cmUsIHVzZSwgZXRjLg~~" },
	{ label: "Chemistry", setSpec: "TENDOkNoZW1pc3RyeQ~~" },
	{ label: "Chinese language and literature", setSpec: "TENDOkNoaW5lc2UgbGFuZ3VhZ2UgYW5kIGxpdGVyYXR1cmU~" },
	{ label: "Chiropractic", setSpec: "TENDOkNoaXJvcHJhY3RpYw~~" },
	{ label: "Christian Denominations", setSpec: "TENDOkNocmlzdGlhbiBEZW5vbWluYXRpb25z" },
	{ label: "Christianity", setSpec: "TENDOkNocmlzdGlhbml0eQ~~" },
	{ label: "Cities. Urban geography", setSpec: "TENDOkNpdGllcy4gVXJiYW4gZ2VvZ3JhcGh5" },
	{ label: "City planning", setSpec: "TENDOkNpdHkgcGxhbm5pbmc~" },
	{ label: "City population. Including children in cities, immigration", setSpec: "TENDOkNpdHkgcG9wdWxhdGlvbi4gSW5jbHVkaW5nIGNoaWxkcmVuIGluIGNpdGllcywgaW1taWdyYXRpb24~" },
	{ label: "Civil law", setSpec: "TENDOkNpdmlsIGxhdw~~" },
	{ label: "Clay industries. Ceramics. Glass", setSpec: "TENDOkNsYXkgaW5kdXN0cmllcy4gQ2VyYW1pY3MuIEdsYXNz" },
	{ label: "Colonies and colonization. Emigration and immigration. International migration", setSpec: "TENDOkNvbG9uaWVzIGFuZCBjb2xvbml6YXRpb24uIEVtaWdyYXRpb24gYW5kIGltbWlncmF0aW9uLiBJbnRlcm5hdGlvbmFsIG1pZ3JhdGlvbg~~" },
	{ label: "Commerce", setSpec: "TENDOkNvbW1lcmNl" },
	{ label: "Commercial geography. Economic geography", setSpec: "TENDOkNvbW1lcmNpYWwgZ2VvZ3JhcGh5LiBFY29ub21pYyBnZW9ncmFwaHk~" },
	{ label: "Commercial law", setSpec: "TENDOkNvbW1lcmNpYWwgbGF3" },
	{ label: "Communication. Mass media", setSpec: "TENDOkNvbW11bmljYXRpb24uIE1hc3MgbWVkaWE~" },
	{ label: "Communities. Classes. Races", setSpec: "TENDOkNvbW11bml0aWVzLiBDbGFzc2VzLiBSYWNlcw~~" },
	{ label: "Comparative grammar", setSpec: "TENDOkNvbXBhcmF0aXZlIGdyYW1tYXI~" },
	{ label: "Comparative law. International uniform law", setSpec: "TENDOkNvbXBhcmF0aXZlIGxhdy4gSW50ZXJuYXRpb25hbCB1bmlmb3JtIGxhdw~~" },
	{ label: "Competition", setSpec: "TENDOkNvbXBldGl0aW9u" },
	{ label: "Computational linguistics. Natural language processing", setSpec: "TENDOkNvbXB1dGF0aW9uYWwgbGluZ3Vpc3RpY3MuIE5hdHVyYWwgbGFuZ3VhZ2UgcHJvY2Vzc2luZw~~" },
	{ label: "Computer applications to medicine. Medical informatics", setSpec: "TENDOkNvbXB1dGVyIGFwcGxpY2F0aW9ucyB0byBtZWRpY2luZS4gTWVkaWNhbCBpbmZvcm1hdGljcw~~" },
	{ label: "Computer engineering. Computer hardware", setSpec: "TENDOkNvbXB1dGVyIGVuZ2luZWVyaW5nLiBDb21wdXRlciBoYXJkd2FyZQ~~" },
	{ label: "Computer software", setSpec: "TENDOkNvbXB1dGVyIHNvZnR3YXJl" },
	{ label: "Consciousness. Cognition", setSpec: "TENDOkNvbnNjaW91c25lc3MuIENvZ25pdGlvbg~~" },
	{ label: "Conservation and restoration of prints", setSpec: "TENDOkNvbnNlcnZhdGlvbiBhbmQgcmVzdG9yYXRpb24gb2YgcHJpbnRz" },
	{ label: "Construction industry", setSpec: "TENDOkNvbnN0cnVjdGlvbiBpbmR1c3RyeQ~~" },
	{ label: "Control engineering systems. Automatic machinery (General)", setSpec: "TENDOkNvbnRyb2wgZW5naW5lZXJpbmcgc3lzdGVtcy4gQXV0b21hdGljIG1hY2hpbmVyeSAoR2VuZXJhbCk~" },
	{ label: "Cookery", setSpec: "TENDOkNvb2tlcnk~" },
	{ label: "Cooperation. Cooperative societies", setSpec: "TENDOkNvb3BlcmF0aW9uLiBDb29wZXJhdGl2ZSBzb2NpZXRpZXM~" },
	{ label: "Costs", setSpec: "TENDOkNvc3Rz" },
	{ label: "Criminal law and procedure", setSpec: "TENDOkNyaW1pbmFsIGxhdyBhbmQgcHJvY2VkdXJl" },
	{ label: "Crisis management. Emergency management. Inflation", setSpec: "TENDOkNyaXNpcyBtYW5hZ2VtZW50LiBFbWVyZ2VuY3kgbWFuYWdlbWVudC4gSW5mbGF0aW9u" },
	{ label: "Crystallography", setSpec: "TENDOkNyeXN0YWxsb2dyYXBoeQ~~" },
	{ label: "Cybernetics", setSpec: "TENDOkN5YmVybmV0aWNz" },
	{ label: "Cytology", setSpec: "TENDOkN5dG9sb2d5" },
	{ label: "Czechoslovakia", setSpec: "TENDOkN6ZWNob3Nsb3Zha2lh" },
	{ label: "Dairy processing. Dairy products", setSpec: "TENDOkRhaXJ5IHByb2Nlc3NpbmcuIERhaXJ5IHByb2R1Y3Rz" },
	{ label: "Dairying", setSpec: "TENDOkRhaXJ5aW5n" },
	{ label: "Dancing", setSpec: "TENDOkRhbmNpbmc~" },
	{ label: "Decorative arts", setSpec: "TENDOkRlY29yYXRpdmUgYXJ0cw~~" },
	{ label: "Demography. Population. Vital events", setSpec: "TENDOkRlbW9ncmFwaHkuIFBvcHVsYXRpb24uIFZpdGFsIGV2ZW50cw~~" },
	{ label: "Dentistry", setSpec: "TENDOkRlbnRpc3RyeQ~~" },
	{ label: "Dermatology", setSpec: "TENDOkRlcm1hdG9sb2d5" },
	{ label: "Descriptive and experimental mechanics", setSpec: "TENDOkRlc2NyaXB0aXZlIGFuZCBleHBlcmltZW50YWwgbWVjaGFuaWNz" },
	{ label: "Details in building design and construction. Including walls, roofs", setSpec: "TENDOkRldGFpbHMgaW4gYnVpbGRpbmcgZGVzaWduIGFuZCBjb25zdHJ1Y3Rpb24uIEluY2x1ZGluZyB3YWxscywgcm9vZnM~" },
	{ label: "Dictionaries and other general reference works", setSpec: "TENDOkRpY3Rpb25hcmllcyBhbmQgb3RoZXIgZ2VuZXJhbCByZWZlcmVuY2Ugd29ya3M~" },
	{ label: "Diplomatics. Archives. Seals", setSpec: "TENDOkRpcGxvbWF0aWNzLiBBcmNoaXZlcy4gU2VhbHM~" },
	{ label: "Disasters and engineering", setSpec: "TENDOkRpc2FzdGVycyBhbmQgZW5naW5lZXJpbmc~" },
	{ label: "Discourse analysis", setSpec: "TENDOkRpc2NvdXJzZSBhbmFseXNpcw~~" },
	{ label: "Diseases of the blood and blood-forming organs", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBibG9vZCBhbmQgYmxvb2QtZm9ybWluZyBvcmdhbnM~" },
	{ label: "Diseases of the circulatory (Cardiovascular) system", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBjaXJjdWxhdG9yeSAoQ2FyZGlvdmFzY3VsYXIpIHN5c3RlbQ~~" },
	{ label: "Diseases of the digestive system. Gastroenterology", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBkaWdlc3RpdmUgc3lzdGVtLiBHYXN0cm9lbnRlcm9sb2d5" },
	{ label: "Diseases of the endocrine glands. Clinical endocrinology", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBlbmRvY3JpbmUgZ2xhbmRzLiBDbGluaWNhbCBlbmRvY3Jpbm9sb2d5" },
	{ label: "Diseases of the genitourinary system. Urology", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBnZW5pdG91cmluYXJ5IHN5c3RlbS4gVXJvbG9neQ~~" },
	{ label: "Diseases of the musculoskeletal system", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSBtdXNjdWxvc2tlbGV0YWwgc3lzdGVt" },
	{ label: "Diseases of the respiratory system", setSpec: "TENDOkRpc2Vhc2VzIG9mIHRoZSByZXNwaXJhdG9yeSBzeXN0ZW0~" },
	{ label: "Distribution or transmission of electric power", setSpec: "TENDOkRpc3RyaWJ1dGlvbiBvciB0cmFuc21pc3Npb24gb2YgZWxlY3RyaWMgcG93ZXI~" },
	{ label: "Doctrinal Theology", setSpec: "TENDOkRvY3RyaW5hbCBUaGVvbG9neQ~~" },
	{ label: "Drama", setSpec: "TENDOkRyYW1h" },
	{ label: "Dramatic representation. The theater", setSpec: "TENDOkRyYW1hdGljIHJlcHJlc2VudGF0aW9uLiBUaGUgdGhlYXRlcg~~" },
	{ label: "Drawing. Design. Illustration", setSpec: "TENDOkRyYXdpbmcuIERlc2lnbi4gSWxsdXN0cmF0aW9u" },
	{ label: "Dynamic and structural geology", setSpec: "TENDOkR5bmFtaWMgYW5kIHN0cnVjdHVyYWwgZ2VvbG9neQ~~" },
	{ label: "Early Christian literature. Fathers of the Church, etc.", setSpec: "TENDOkVhcmx5IENocmlzdGlhbiBsaXRlcmF0dXJlLiBGYXRoZXJzIG9mIHRoZSBDaHVyY2gsIGV0Yy4~" },
	{ label: "Earthwork. Foundations", setSpec: "TENDOkVhcnRod29yay4gRm91bmRhdGlvbnM~" },
	{ label: "Ecology", setSpec: "TENDOkVjb2xvZ3k~" },
	{ label: "Economic biology", setSpec: "TENDOkVjb25vbWljIGJpb2xvZ3k~" },
	{ label: "Economic geography of the oceans (General)", setSpec: "TENDOkVjb25vbWljIGdlb2dyYXBoeSBvZiB0aGUgb2NlYW5zIChHZW5lcmFsKQ~~" },
	{ label: "Economic growth, development, planning", setSpec: "TENDOkVjb25vbWljIGdyb3d0aCwgZGV2ZWxvcG1lbnQsIHBsYW5uaW5n" },
	{ label: "Economic history and conditions", setSpec: "TENDOkVjb25vbWljIGhpc3RvcnkgYW5kIGNvbmRpdGlvbnM~" },
	{ label: "Economic theory. Demography", setSpec: "TENDOkVjb25vbWljIHRoZW9yeS4gRGVtb2dyYXBoeQ~~" },
	{ label: "Economics as a science", setSpec: "TENDOkVjb25vbWljcyBhcyBhIHNjaWVuY2U~" },
	{ label: "Education", setSpec: "TENDOkVkdWNhdGlvbg~~" },
	{ label: "Education (General)", setSpec: "TENDOkVkdWNhdGlvbiAoR2VuZXJhbCk~" },
	{ label: "Electric apparatus and materials. Electric circuits. Electric networks", setSpec: "TENDOkVsZWN0cmljIGFwcGFyYXR1cyBhbmQgbWF0ZXJpYWxzLiBFbGVjdHJpYyBjaXJjdWl0cy4gRWxlY3RyaWMgbmV0d29ya3M~" },
	{ label: "Electrical engineering. Electronics. Nuclear engineering", setSpec: "TENDOkVsZWN0cmljYWwgZW5naW5lZXJpbmcuIEVsZWN0cm9uaWNzLiBOdWNsZWFyIGVuZ2luZWVyaW5n" },
	{ label: "Electricity", setSpec: "TENDOkVsZWN0cmljaXR5" },
	{ label: "Electricity and magnetism", setSpec: "TENDOkVsZWN0cmljaXR5IGFuZCBtYWduZXRpc20~" },
	{ label: "Electronic computers. Computer science", setSpec: "TENDOkVsZWN0cm9uaWMgY29tcHV0ZXJzLiBDb21wdXRlciBzY2llbmNl" },
	{ label: "Electronics", setSpec: "TENDOkVsZWN0cm9uaWNz" },
	{ label: "Elementary particle physics", setSpec: "TENDOkVsZW1lbnRhcnkgcGFydGljbGUgcGh5c2ljcw~~" },
	{ label: "Employee participation in management. Employee ownership. Industrial democracy. Works councils", setSpec: "TENDOkVtcGxveWVlIHBhcnRpY2lwYXRpb24gaW4gbWFuYWdlbWVudC4gRW1wbG95ZWUgb3duZXJzaGlwLiBJbmR1c3RyaWFsIGRlbW9jcmFjeS4gV29ya3MgY291bmNpbHM~" },
	{ label: "Encyclopedias", setSpec: "TENDOkVuY3ljbG9wZWRpYXM~" },
	{ label: "Energy conservation", setSpec: "TENDOkVuZXJneSBjb25zZXJ2YXRpb24~" },
	{ label: "Energy industries. Energy policy. Fuel trade", setSpec: "TENDOkVuZXJneSBpbmR1c3RyaWVzLiBFbmVyZ3kgcG9saWN5LiBGdWVsIHRyYWRl" },
	{ label: "Engineering (General). Civil engineering (General)", setSpec: "TENDOkVuZ2luZWVyaW5nIChHZW5lcmFsKS4gQ2l2aWwgZW5naW5lZXJpbmcgKEdlbmVyYWwp" },
	{ label: "Engineering design", setSpec: "TENDOkVuZ2luZWVyaW5nIGRlc2lnbg~~" },
	{ label: "Engineering economy", setSpec: "TENDOkVuZ2luZWVyaW5nIGVjb25vbXk~" },
	{ label: "Engineering geology. Rock mechanics. Soil mechanics. Underground construction", setSpec: "TENDOkVuZ2luZWVyaW5nIGdlb2xvZ3kuIFJvY2sgbWVjaGFuaWNzLiBTb2lsIG1lY2hhbmljcy4gVW5kZXJncm91bmQgY29uc3RydWN0aW9u" },
	{ label: "Engineering machinery, tools, and implements", setSpec: "TENDOkVuZ2luZWVyaW5nIG1hY2hpbmVyeSwgdG9vbHMsIGFuZCBpbXBsZW1lbnRz" },
	{ label: "English language", setSpec: "TENDOkVuZ2xpc2ggbGFuZ3VhZ2U~" },
	{ label: "English literature", setSpec: "TENDOkVuZ2xpc2ggbGl0ZXJhdHVyZQ~~" },
	{ label: "Environmental effects of industries and plants", setSpec: "TENDOkVudmlyb25tZW50YWwgZWZmZWN0cyBvZiBpbmR1c3RyaWVzIGFuZCBwbGFudHM~" },
	{ label: "Environmental engineering", setSpec: "TENDOkVudmlyb25tZW50YWwgZW5naW5lZXJpbmc~" },
	{ label: "Environmental law", setSpec: "TENDOkVudmlyb25tZW50YWwgbGF3" },
	{ label: "Environmental pollution", setSpec: "TENDOkVudmlyb25tZW50YWwgcG9sbHV0aW9u" },
	{ label: "Environmental protection", setSpec: "TENDOkVudmlyb25tZW50YWwgcHJvdGVjdGlvbg~~" },
	{ label: "Environmental sciences", setSpec: "TENDOkVudmlyb25tZW50YWwgc2NpZW5jZXM~" },
	{ label: "Environmental technology. Sanitary engineering", setSpec: "TENDOkVudmlyb25tZW50YWwgdGVjaG5vbG9neS4gU2FuaXRhcnkgZW5naW5lZXJpbmc~" },
	{ label: "Epistemology. Theory of knowledge", setSpec: "TENDOkVwaXN0ZW1vbG9neS4gVGhlb3J5IG9mIGtub3dsZWRnZQ~~" },
	{ label: "Ethics", setSpec: "TENDOkV0aGljcw~~" },
	{ label: "Ethnology. Social and cultural anthropology", setSpec: "TENDOkV0aG5vbG9neS4gU29jaWFsIGFuZCBjdWx0dXJhbCBhbnRocm9wb2xvZ3k~" },
	{ label: "Europe (General)", setSpec: "TENDOkV1cm9wZSAoR2VuZXJhbCk~" },
	{ label: "Evolution", setSpec: "TENDOkV2b2x1dGlvbg~~" },
	{ label: "Explosives and pyrotechnics", setSpec: "TENDOkV4cGxvc2l2ZXMgYW5kIHB5cm90ZWNobmljcw~~" },
	{ label: "Fermentation industries. Beverages. Alcohol", setSpec: "TENDOkZlcm1lbnRhdGlvbiBpbmR1c3RyaWVzLiBCZXZlcmFnZXMuIEFsY29ob2w~" },
	{ label: "Finance", setSpec: "TENDOkZpbmFuY2U~" },
	{ label: "Fine Arts", setSpec: "TENDOkZpbmUgQXJ0cw~~" },
	{ label: "Finland", setSpec: "TENDOkZpbmxhbmQ~" },
	{ label: "Finnic. Baltic-Finnic", setSpec: "TENDOkZpbm5pYy4gQmFsdGljLUZpbm5pYw~~" },
	{ label: "Folklore", setSpec: "TENDOkZvbGtsb3Jl" },
	{ label: "Food processing and manufacture", setSpec: "TENDOkZvb2QgcHJvY2Vzc2luZyBhbmQgbWFudWZhY3R1cmU~" },
	{ label: "Forestry", setSpec: "TENDOkZvcmVzdHJ5" },
	{ label: "Fossil man. Human paleontology", setSpec: "TENDOkZvc3NpbCBtYW4uIEh1bWFuIHBhbGVvbnRvbG9neQ~~" },
	{ label: "French literature - Italian literature - Spanish literature - Portuguese literature", setSpec: "TENDOkZyZW5jaCBsaXRlcmF0dXJlIC0gSXRhbGlhbiBsaXRlcmF0dXJlIC0gU3BhbmlzaCBsaXRlcmF0dXJlIC0gUG9ydHVndWVzZSBsaXRlcmF0dXJl" },
	{ label: "Fuel", setSpec: "TENDOkZ1ZWw~" },
	{ label: "Garden cities. The city beautiful", setSpec: "TENDOkdhcmRlbiBjaXRpZXMuIFRoZSBjaXR5IGJlYXV0aWZ1bA~~" },
	{ label: "Gas industry", setSpec: "TENDOkdhcyBpbmR1c3RyeQ~~" },
	{ label: "Genealogy", setSpec: "TENDOkdlbmVhbG9neQ~~" },
	{ label: "General Works", setSpec: "TENDOkdlbmVyYWwgV29ya3M~" },
	{ label: "General bibliography", setSpec: "TENDOkdlbmVyYWwgYmlibGlvZ3JhcGh5" },
	{ label: "General works", setSpec: "TENDOkdlbmVyYWwgd29ya3M~" },
	{ label: "General. Including alchemy", setSpec: "TENDOkdlbmVyYWwuIEluY2x1ZGluZyBhbGNoZW15" },
	{ label: "General. Including nature conservation, geographical distribution", setSpec: "TENDOkdlbmVyYWwuIEluY2x1ZGluZyBuYXR1cmUgY29uc2VydmF0aW9uLCBnZW9ncmFwaGljYWwgZGlzdHJpYnV0aW9u" },
	{ label: "Genetics", setSpec: "TENDOkdlbmV0aWNz" },
	{ label: "Geodesy", setSpec: "TENDOkdlb2Rlc3k~" },
	{ label: "Geography (General)", setSpec: "TENDOkdlb2dyYXBoeSAoR2VuZXJhbCk~" },
	{ label: "Geography. Anthropology. Recreation", setSpec: "TENDOkdlb2dyYXBoeS4gQW50aHJvcG9sb2d5LiBSZWNyZWF0aW9u" },
	{ label: "Geology", setSpec: "TENDOkdlb2xvZ3k~" },
	{ label: "Geomagnetism", setSpec: "TENDOkdlb21hZ25ldGlzbQ~~" },
	{ label: "Geophysics. Cosmic physics", setSpec: "TENDOkdlb3BoeXNpY3MuIENvc21pYyBwaHlzaWNz" },
	{ label: "Geriatrics", setSpec: "TENDOkdlcmlhdHJpY3M~" },
	{ label: "German literature", setSpec: "TENDOkdlcm1hbiBsaXRlcmF0dXJl" },
	{ label: "Germanic languages. Scandinavian languages", setSpec: "TENDOkdlcm1hbmljIGxhbmd1YWdlcy4gU2NhbmRpbmF2aWFuIGxhbmd1YWdlcw~~" },
	{ label: "Greek language and literature. Latin language and literature", setSpec: "TENDOkdyZWVrIGxhbmd1YWdlIGFuZCBsaXRlcmF0dXJlLiBMYXRpbiBsYW5ndWFnZSBhbmQgbGl0ZXJhdHVyZQ~~" },
	{ label: "Greek philology and language", setSpec: "TENDOkdyZWVrIHBoaWxvbG9neSBhbmQgbGFuZ3VhZ2U~" },
	{ label: "Gynecology and obstetrics", setSpec: "TENDOkd5bmVjb2xvZ3kgYW5kIG9ic3RldHJpY3M~" },
	{ label: "Handicrafts. Arts and crafts", setSpec: "TENDOkhhbmRpY3JhZnRzLiBBcnRzIGFuZCBjcmFmdHM~" },
	{ label: "Harbors and coast protective works. Coastal engineering. Lighthouses", setSpec: "TENDOkhhcmJvcnMgYW5kIGNvYXN0IHByb3RlY3RpdmUgd29ya3MuIENvYXN0YWwgZW5naW5lZXJpbmcuIExpZ2h0aG91c2Vz" },
	{ label: "Hazardous substances and their disposal", setSpec: "TENDOkhhemFyZG91cyBzdWJzdGFuY2VzIGFuZCB0aGVpciBkaXNwb3NhbA~~" },
	{ label: "Heat", setSpec: "TENDOkhlYXQ~" },
	{ label: "Heating and ventilation. Air conditioning", setSpec: "TENDOkhlYXRpbmcgYW5kIHZlbnRpbGF0aW9uLiBBaXIgY29uZGl0aW9uaW5n" },
	{ label: "Highway engineering. Roads and pavements", setSpec: "TENDOkhpZ2h3YXkgZW5naW5lZXJpbmcuIFJvYWRzIGFuZCBwYXZlbWVudHM~" },
	{ label: "History", setSpec: "TENDOkhpc3Rvcnk~" },
	{ label: "History (General)", setSpec: "TENDOkhpc3RvcnkgKEdlbmVyYWwp" },
	{ label: "History (General) and history of Europe", setSpec: "TENDOkhpc3RvcnkgKEdlbmVyYWwpIGFuZCBoaXN0b3J5IG9mIEV1cm9wZQ~~" },
	{ label: "History America", setSpec: "TENDOkhpc3RvcnkgQW1lcmljYQ~~" },
	{ label: "History and principles of religions", setSpec: "TENDOkhpc3RvcnkgYW5kIHByaW5jaXBsZXMgb2YgcmVsaWdpb25z" },
	{ label: "History of Africa", setSpec: "TENDOkhpc3Rvcnkgb2YgQWZyaWNh" },
	{ label: "History of Asia", setSpec: "TENDOkhpc3Rvcnkgb2YgQXNpYQ~~" },
	{ label: "History of Austria. Liechtenstein. Hungary. Czechoslovakia", setSpec: "TENDOkhpc3Rvcnkgb2YgQXVzdHJpYS4gTGllY2h0ZW5zdGVpbi4gSHVuZ2FyeS4gQ3plY2hvc2xvdmFraWE~" },
	{ label: "History of Balkan Peninsula", setSpec: "TENDOkhpc3Rvcnkgb2YgQmFsa2FuIFBlbmluc3VsYQ~~" },
	{ label: "History of Central Europe", setSpec: "TENDOkhpc3Rvcnkgb2YgQ2VudHJhbCBFdXJvcGU~" },
	{ label: "History of Civilization", setSpec: "TENDOkhpc3Rvcnkgb2YgQ2l2aWxpemF0aW9u" },
	{ label: "History of Eastern Europe", setSpec: "TENDOkhpc3Rvcnkgb2YgRWFzdGVybiBFdXJvcGU~" },
	{ label: "History of France", setSpec: "TENDOkhpc3Rvcnkgb2YgRnJhbmNl" },
	{ label: "History of Germany", setSpec: "TENDOkhpc3Rvcnkgb2YgR2VybWFueQ~~" },
	{ label: "History of Great Britain", setSpec: "TENDOkhpc3Rvcnkgb2YgR3JlYXQgQnJpdGFpbg~~" },
	{ label: "History of Greece", setSpec: "TENDOkhpc3Rvcnkgb2YgR3JlZWNl" },
	{ label: "History of Italy", setSpec: "TENDOkhpc3Rvcnkgb2YgSXRhbHk~" },
	{ label: "History of Law", setSpec: "TENDOkhpc3Rvcnkgb2YgTGF3" },
	{ label: "History of Low Countries - Benelux Countries", setSpec: "TENDOkhpc3Rvcnkgb2YgTG93IENvdW50cmllcyAtIEJlbmVsdXggQ291bnRyaWVz" },
	{ label: "History of Northern Europe. Scandinavia", setSpec: "TENDOkhpc3Rvcnkgb2YgTm9ydGhlcm4gRXVyb3BlLiBTY2FuZGluYXZpYQ~~" },
	{ label: "History of Oceania (South Seas)", setSpec: "TENDOkhpc3Rvcnkgb2YgT2NlYW5pYSAoU291dGggU2Vhcyk~" },
	{ label: "History of Poland", setSpec: "TENDOkhpc3Rvcnkgb2YgUG9sYW5k" },
	{ label: "History of Portugal", setSpec: "TENDOkhpc3Rvcnkgb2YgUG9ydHVnYWw~" },
	{ label: "History of Russia. Soviet Union. Former Soviet Republics", setSpec: "TENDOkhpc3Rvcnkgb2YgUnVzc2lhLiBTb3ZpZXQgVW5pb24uIEZvcm1lciBTb3ZpZXQgUmVwdWJsaWNz" },
	{ label: "History of Spain", setSpec: "TENDOkhpc3Rvcnkgb2YgU3BhaW4~" },
	{ label: "History of education", setSpec: "TENDOkhpc3Rvcnkgb2YgZWR1Y2F0aW9u" },
	{ label: "History of medicine. Medical expeditions", setSpec: "TENDOkhpc3Rvcnkgb2YgbWVkaWNpbmUuIE1lZGljYWwgZXhwZWRpdGlvbnM~" },
	{ label: "History of scholarship and learning. The humanities", setSpec: "TENDOkhpc3Rvcnkgb2Ygc2Nob2xhcnNoaXAgYW5kIGxlYXJuaW5nLiBUaGUgaHVtYW5pdGllcw~~" },
	{ label: "History of specific doctrines and movements. Heresies and schisms", setSpec: "TENDOkhpc3Rvcnkgb2Ygc3BlY2lmaWMgZG9jdHJpbmVzIGFuZCBtb3ZlbWVudHMuIEhlcmVzaWVzIGFuZCBzY2hpc21z" },
	{ label: "History of the Greco-Roman World", setSpec: "TENDOkhpc3Rvcnkgb2YgdGhlIEdyZWNvLVJvbWFuIFdvcmxk" },
	{ label: "History of the arts", setSpec: "TENDOkhpc3Rvcnkgb2YgdGhlIGFydHM~" },
	{ label: "Home economics", setSpec: "TENDOkhvbWUgZWNvbm9taWNz" },
	{ label: "Homeopathy", setSpec: "TENDOkhvbWVvcGF0aHk~" },
	{ label: "Hospitality industry. Hotels, clubs, restaurants, etc. Food service", setSpec: "TENDOkhvc3BpdGFsaXR5IGluZHVzdHJ5LiBIb3RlbHMsIGNsdWJzLCByZXN0YXVyYW50cywgZXRjLiBGb29kIHNlcnZpY2U~" },
	{ label: "Human anatomy", setSpec: "TENDOkh1bWFuIGFuYXRvbXk~" },
	{ label: "Human ecology. Anthropogeography", setSpec: "TENDOkh1bWFuIGVjb2xvZ3kuIEFudGhyb3BvZ2VvZ3JhcGh5" },
	{ label: "Human evolution", setSpec: "TENDOkh1bWFuIGV2b2x1dGlvbg~~" },
	{ label: "Human settlements. Communities", setSpec: "TENDOkh1bWFuIHNldHRsZW1lbnRzLiBDb21tdW5pdGllcw~~" },
	{ label: "Hungary", setSpec: "TENDOkh1bmdhcnk~" },
	{ label: "Hydraulic engineering", setSpec: "TENDOkh5ZHJhdWxpYyBlbmdpbmVlcmluZw~~" },
	{ label: "Immunologic diseases. Allergy", setSpec: "TENDOkltbXVub2xvZ2ljIGRpc2Vhc2VzLiBBbGxlcmd5" },
	{ label: "Indo-Iranian languages and literature", setSpec: "TENDOkluZG8tSXJhbmlhbiBsYW5ndWFnZXMgYW5kIGxpdGVyYXR1cmU~" },
	{ label: "Industrial arbitration. Meditation and conciliation", setSpec: "TENDOkluZHVzdHJpYWwgYXJiaXRyYXRpb24uIE1lZGl0YXRpb24gYW5kIGNvbmNpbGlhdGlvbg~~" },
	{ label: "Industrial directories", setSpec: "TENDOkluZHVzdHJpYWwgZGlyZWN0b3JpZXM~" },
	{ label: "Industrial electrochemistry", setSpec: "TENDOkluZHVzdHJpYWwgZWxlY3Ryb2NoZW1pc3RyeQ~~" },
	{ label: "Industrial engineering. Management engineering", setSpec: "TENDOkluZHVzdHJpYWwgZW5naW5lZXJpbmcuIE1hbmFnZW1lbnQgZW5naW5lZXJpbmc~" },
	{ label: "Industrial hygiene. Industrial welfare", setSpec: "TENDOkluZHVzdHJpYWwgaHlnaWVuZS4gSW5kdXN0cmlhbCB3ZWxmYXJl" },
	{ label: "Industrial medicine. Industrial hygiene", setSpec: "TENDOkluZHVzdHJpYWwgbWVkaWNpbmUuIEluZHVzdHJpYWwgaHlnaWVuZQ~~" },
	{ label: "Industrial productivity", setSpec: "TENDOkluZHVzdHJpYWwgcHJvZHVjdGl2aXR5" },
	{ label: "Industrial psychology", setSpec: "TENDOkluZHVzdHJpYWwgcHN5Y2hvbG9neQ~~" },
	{ label: "Industrial relations", setSpec: "TENDOkluZHVzdHJpYWwgcmVsYXRpb25z" },
	{ label: "Industrial safety. Industrial accident prevention", setSpec: "TENDOkluZHVzdHJpYWwgc2FmZXR5LiBJbmR1c3RyaWFsIGFjY2lkZW50IHByZXZlbnRpb24~" },
	{ label: "Industrial sociology. Social conditions of labor", setSpec: "TENDOkluZHVzdHJpYWwgc29jaW9sb2d5LiBTb2NpYWwgY29uZGl0aW9ucyBvZiBsYWJvcg~~" },
	{ label: "Industries. Land use. Labor", setSpec: "TENDOkluZHVzdHJpZXMuIExhbmQgdXNlLiBMYWJvcg~~" },
	{ label: "Industry", setSpec: "TENDOkluZHVzdHJ5" },
	{ label: "Infectious and parasitic diseases", setSpec: "TENDOkluZmVjdGlvdXMgYW5kIHBhcmFzaXRpYyBkaXNlYXNlcw~~" },
	{ label: "Information resources (General)", setSpec: "TENDOkluZm9ybWF0aW9uIHJlc291cmNlcyAoR2VuZXJhbCk~" },
	{ label: "Information technology", setSpec: "TENDOkluZm9ybWF0aW9uIHRlY2hub2xvZ3k~" },
	{ label: "Information theory", setSpec: "TENDOkluZm9ybWF0aW9uIHRoZW9yeQ~~" },
	{ label: "Inorganic chemistry", setSpec: "TENDOklub3JnYW5pYyBjaGVtaXN0cnk~" },
	{ label: "Instruments and machines", setSpec: "TENDOkluc3RydW1lbnRzIGFuZCBtYWNoaW5lcw~~" },
	{ label: "Insurance", setSpec: "TENDOkluc3VyYW5jZQ~~" },
	{ label: "Internal medicine", setSpec: "TENDOkludGVybmFsIG1lZGljaW5l" },
	{ label: "International relations", setSpec: "TENDOkludGVybmF0aW9uYWwgcmVsYXRpb25z" },
	{ label: "Irrigation engineering. Reclamation of wasteland. Drainage", setSpec: "TENDOklycmlnYXRpb24gZW5naW5lZXJpbmcuIFJlY2xhbWF0aW9uIG9mIHdhc3RlbGFuZC4gRHJhaW5hZ2U~" },
	{ label: "Islam", setSpec: "TENDOklzbGFt" },
	{ label: "Islam. Bahai Faith. Theosophy, etc.", setSpec: "TENDOklzbGFtLiBCYWhhaSBGYWl0aC4gVGhlb3NvcGh5LCBldGMu" },
	{ label: "Islamic law", setSpec: "TENDOklzbGFtaWMgbGF3" },
	{ label: "Japanese language and literature", setSpec: "TENDOkphcGFuZXNlIGxhbmd1YWdlIGFuZCBsaXRlcmF0dXJl" },
	{ label: "Journalism. The periodical press, etc.", setSpec: "TENDOkpvdXJuYWxpc20uIFRoZSBwZXJpb2RpY2FsIHByZXNzLCBldGMu" },
	{ label: "Judaism", setSpec: "TENDOkp1ZGFpc20~" },
	{ label: "Jurisprudence. Philosophy and theory of law", setSpec: "TENDOkp1cmlzcHJ1ZGVuY2UuIFBoaWxvc29waHkgYW5kIHRoZW9yeSBvZiBsYXc~" },
	{ label: "Labor in politics. Political activity of the working class", setSpec: "TENDOkxhYm9yIGluIHBvbGl0aWNzLiBQb2xpdGljYWwgYWN0aXZpdHkgb2YgdGhlIHdvcmtpbmcgY2xhc3M~" },
	{ label: "Labor market. Labor supply. Labor demand", setSpec: "TENDOkxhYm9yIG1hcmtldC4gTGFib3Igc3VwcGx5LiBMYWJvciBkZW1hbmQ~" },
	{ label: "Labor policy. Labor and the state", setSpec: "TENDOkxhYm9yIHBvbGljeS4gTGFib3IgYW5kIHRoZSBzdGF0ZQ~~" },
	{ label: "Labor systems", setSpec: "TENDOkxhYm9yIHN5c3RlbXM~" },
	{ label: "Labor. Work. Working class", setSpec: "TENDOkxhYm9yLiBXb3JrLiBXb3JraW5nIGNsYXNz" },
	{ label: "Land reform. Agrarian reform", setSpec: "TENDOkxhbmQgcmVmb3JtLiBBZ3JhcmlhbiByZWZvcm0~" },
	{ label: "Land tenure", setSpec: "TENDOkxhbmQgdGVudXJl" },
	{ label: "Land use", setSpec: "TENDOkxhbmQgdXNl" },
	{ label: "Language acquisition", setSpec: "TENDOkxhbmd1YWdlIGFjcXVpc2l0aW9u" },
	{ label: "Language and Literature", setSpec: "TENDOkxhbmd1YWdlIGFuZCBMaXRlcmF0dXJl" },
	{ label: "Language. Linguistic theory. Comparative grammar", setSpec: "TENDOkxhbmd1YWdlLiBMaW5ndWlzdGljIHRoZW9yeS4gQ29tcGFyYXRpdmUgZ3JhbW1hcg~~" },
	{ label: "Languages and literature of Eastern Asia, Africa, Oceania", setSpec: "TENDOkxhbmd1YWdlcyBhbmQgbGl0ZXJhdHVyZSBvZiBFYXN0ZXJuIEFzaWEsIEFmcmljYSwgT2NlYW5pYQ~~" },
	{ label: "Large industry. Factory system. Big business", setSpec: "TENDOkxhcmdlIGluZHVzdHJ5LiBGYWN0b3J5IHN5c3RlbS4gQmlnIGJ1c2luZXNz" },
	{ label: "Latin America. Spanish America", setSpec: "TENDOkxhdGluIEFtZXJpY2EuIFNwYW5pc2ggQW1lcmljYQ~~" },
	{ label: "Law", setSpec: "TENDOkxhdw~~" },
	{ label: "Law in general. Comparative and uniform law. Jurisprudence", setSpec: "TENDOkxhdyBpbiBnZW5lcmFsLiBDb21wYXJhdGl2ZSBhbmQgdW5pZm9ybSBsYXcuIEp1cmlzcHJ1ZGVuY2U~" },
	{ label: "Law of Europe", setSpec: "TENDOkxhdyBvZiBFdXJvcGU~" },
	{ label: "Law of nations", setSpec: "TENDOkxhdyBvZiBuYXRpb25z" },
	{ label: "Lexicography", setSpec: "TENDOkxleGljb2dyYXBoeQ~~" },
	{ label: "Life", setSpec: "TENDOkxpZmU~" },
	{ label: "Literature (General)", setSpec: "TENDOkxpdGVyYXR1cmUgKEdlbmVyYWwp" },
	{ label: "Literature on music", setSpec: "TENDOkxpdGVyYXR1cmUgb24gbXVzaWM~" },
	{ label: "Logic", setSpec: "TENDOkxvZ2lj" },
	{ label: "Low temperature engineering. Cryogenic engineering. Refrigeration", setSpec: "TENDOkxvdyB0ZW1wZXJhdHVyZSBlbmdpbmVlcmluZy4gQ3J5b2dlbmljIGVuZ2luZWVyaW5nLiBSZWZyaWdlcmF0aW9u" },
	{ label: "Machine design and drawing", setSpec: "TENDOk1hY2hpbmUgZGVzaWduIGFuZCBkcmF3aW5n" },
	{ label: "Management information systems", setSpec: "TENDOk1hbmFnZW1lbnQgaW5mb3JtYXRpb24gc3lzdGVtcw~~" },
	{ label: "Management of special enterprises", setSpec: "TENDOk1hbmFnZW1lbnQgb2Ygc3BlY2lhbCBlbnRlcnByaXNlcw~~" },
	{ label: "Management. Industrial management", setSpec: "TENDOk1hbmFnZW1lbnQuIEluZHVzdHJpYWwgbWFuYWdlbWVudA~~" },
	{ label: "Manners and customs (General)", setSpec: "TENDOk1hbm5lcnMgYW5kIGN1c3RvbXMgKEdlbmVyYWwp" },
	{ label: "Manufactures", setSpec: "TENDOk1hbnVmYWN0dXJlcw~~" },
	{ label: "Manufacturing industries", setSpec: "TENDOk1hbnVmYWN0dXJpbmcgaW5kdXN0cmllcw~~" },
	{ label: "Maps", setSpec: "TENDOk1hcHM~" },
	{ label: "Marketing. Distribution of products", setSpec: "TENDOk1hcmtldGluZy4gRGlzdHJpYnV0aW9uIG9mIHByb2R1Y3Rz" },
	{ label: "Materials of engineering and construction. Mechanics of materials", setSpec: "TENDOk1hdGVyaWFscyBvZiBlbmdpbmVlcmluZyBhbmQgY29uc3RydWN0aW9uLiBNZWNoYW5pY3Mgb2YgbWF0ZXJpYWxz" },
	{ label: "Mathematical geography. Cartography", setSpec: "TENDOk1hdGhlbWF0aWNhbCBnZW9ncmFwaHkuIENhcnRvZ3JhcGh5" },
	{ label: "Mathematics", setSpec: "TENDOk1hdGhlbWF0aWNz" },
	{ label: "Mechanical drawing. Engineering graphics", setSpec: "TENDOk1lY2hhbmljYWwgZHJhd2luZy4gRW5naW5lZXJpbmcgZ3JhcGhpY3M~" },
	{ label: "Mechanical engineering and machinery", setSpec: "TENDOk1lY2hhbmljYWwgZW5naW5lZXJpbmcgYW5kIG1hY2hpbmVyeQ~~" },
	{ label: "Mechanical industries", setSpec: "TENDOk1lY2hhbmljYWwgaW5kdXN0cmllcw~~" },
	{ label: "Mechanics of engineering. Applied mechanics", setSpec: "TENDOk1lY2hhbmljcyBvZiBlbmdpbmVlcmluZy4gQXBwbGllZCBtZWNoYW5pY3M~" },
	{ label: "Medical emergencies. Critical care. Intensive care. First aid", setSpec: "TENDOk1lZGljYWwgZW1lcmdlbmNpZXMuIENyaXRpY2FsIGNhcmUuIEludGVuc2l2ZSBjYXJlLiBGaXJzdCBhaWQ~" },
	{ label: "Medical legislation", setSpec: "TENDOk1lZGljYWwgbGVnaXNsYXRpb24~" },
	{ label: "Medical philosophy. Medical ethics", setSpec: "TENDOk1lZGljYWwgcGhpbG9zb3BoeS4gTWVkaWNhbCBldGhpY3M~" },
	{ label: "Medical physics. Medical radiology. Nuclear medicine", setSpec: "TENDOk1lZGljYWwgcGh5c2ljcy4gTWVkaWNhbCByYWRpb2xvZ3kuIE51Y2xlYXIgbWVkaWNpbmU~" },
	{ label: "Medical technology", setSpec: "TENDOk1lZGljYWwgdGVjaG5vbG9neQ~~" },
	{ label: "Medicine", setSpec: "TENDOk1lZGljaW5l" },
	{ label: "Medicine (General)", setSpec: "TENDOk1lZGljaW5lIChHZW5lcmFsKQ~~" },
	{ label: "Medieval history", setSpec: "TENDOk1lZGlldmFsIGhpc3Rvcnk~" },
	{ label: "Men", setSpec: "TENDOk1lbg~~" },
	{ label: "Mental healing", setSpec: "TENDOk1lbnRhbCBoZWFsaW5n" },
	{ label: "Metaphysics", setSpec: "TENDOk1ldGFwaHlzaWNz" },
	{ label: "Meteorology. Climatology", setSpec: "TENDOk1ldGVvcm9sb2d5LiBDbGltYXRvbG9neQ~~" },
	{ label: "Metropolitan areas", setSpec: "TENDOk1ldHJvcG9saXRhbiBhcmVhcw~~" },
	{ label: "Microbial ecology", setSpec: "TENDOk1pY3JvYmlhbCBlY29sb2d5" },
	{ label: "Microbiology", setSpec: "TENDOk1pY3JvYmlvbG9neQ~~" },
	{ label: "Microscopy", setSpec: "TENDOk1pY3Jvc2NvcHk~" },
	{ label: "Military Science", setSpec: "TENDOk1pbGl0YXJ5IFNjaWVuY2U~" },
	{ label: "Mineral industries. Metal trade", setSpec: "TENDOk1pbmVyYWwgaW5kdXN0cmllcy4gTWV0YWwgdHJhZGU~" },
	{ label: "Mineralogy", setSpec: "TENDOk1pbmVyYWxvZ3k~" },
	{ label: "Mining engineering. Metallurgy", setSpec: "TENDOk1pbmluZyBlbmdpbmVlcmluZy4gTWV0YWxsdXJneQ~~" },
	{ label: "Miscellaneous industries and trades", setSpec: "TENDOk1pc2NlbGxhbmVvdXMgaW5kdXN0cmllcyBhbmQgdHJhZGVz" },
	{ label: "Miscellaneous systems and treatments", setSpec: "TENDOk1pc2NlbGxhbmVvdXMgc3lzdGVtcyBhbmQgdHJlYXRtZW50cw~~" },
	{ label: "Modern", setSpec: "TENDOk1vZGVybg~~" },
	{ label: "Modern history, 1453-", setSpec: "TENDOk1vZGVybiBoaXN0b3J5LCAxNDUzLQ~~" },
	{ label: "Moral theology", setSpec: "TENDOk1vcmFsIHRoZW9sb2d5" },
	{ label: "Motion pictures", setSpec: "TENDOk1vdGlvbiBwaWN0dXJlcw~~" },
	{ label: "Motor vehicles. Aeronautics. Astronautics", setSpec: "TENDOk1vdG9yIHZlaGljbGVzLiBBZXJvbmF1dGljcy4gQXN0cm9uYXV0aWNz" },
	{ label: "Municipal ownership", setSpec: "TENDOk11bmljaXBhbCBvd25lcnNoaXA~" },
	{ label: "Municipal refuse. Solid wastes", setSpec: "TENDOk11bmljaXBhbCByZWZ1c2UuIFNvbGlkIHdhc3Rlcw~~" },
	{ label: "Museums. Collectors and collecting", setSpec: "TENDOk11c2V1bXMuIENvbGxlY3RvcnMgYW5kIGNvbGxlY3Rpbmc~" },
	{ label: "Music", setSpec: "TENDOk11c2lj" },
	{ label: "Music and books on Music", setSpec: "TENDOk11c2ljIGFuZCBib29rcyBvbiBNdXNpYw~~" },
	{ label: "Musical instruction and study", setSpec: "TENDOk11c2ljYWwgaW5zdHJ1Y3Rpb24gYW5kIHN0dWR5" },
	{ label: "Natural history (General)", setSpec: "TENDOk5hdHVyYWwgaGlzdG9yeSAoR2VuZXJhbCk~" },
	{ label: "Naval Science", setSpec: "TENDOk5hdmFsIFNjaWVuY2U~" },
	{ label: "Naval architecture. Shipbuilding. Marine engineering", setSpec: "TENDOk5hdmFsIGFyY2hpdGVjdHVyZS4gU2hpcGJ1aWxkaW5nLiBNYXJpbmUgZW5naW5lZXJpbmc~" },
	{ label: "Neoplasms. Tumors. Oncology. Including cancer and carcinogens", setSpec: "TENDOk5lb3BsYXNtcy4gVHVtb3JzLiBPbmNvbG9neS4gSW5jbHVkaW5nIGNhbmNlciBhbmQgY2FyY2lub2dlbnM~" },
	{ label: "Neurology. Diseases of the nervous system", setSpec: "TENDOk5ldXJvbG9neS4gRGlzZWFzZXMgb2YgdGhlIG5lcnZvdXMgc3lzdGVt" },
	{ label: "Neurophysiology and neuropsychology", setSpec: "TENDOk5ldXJvcGh5c2lvbG9neSBhbmQgbmV1cm9wc3ljaG9sb2d5" },
	{ label: "Neurosciences. Biological psychiatry. Neuropsychiatry", setSpec: "TENDOk5ldXJvc2NpZW5jZXMuIEJpb2xvZ2ljYWwgcHN5Y2hpYXRyeS4gTmV1cm9wc3ljaGlhdHJ5" },
	{ label: "New Testament", setSpec: "TENDOk5ldyBUZXN0YW1lbnQ~" },
	{ label: "Newspapers", setSpec: "TENDOk5ld3NwYXBlcnM~" },
	{ label: "North Germanic. Scandinavian", setSpec: "TENDOk5vcnRoIEdlcm1hbmljLiBTY2FuZGluYXZpYW4~" },
	{ label: "Norway", setSpec: "TENDOk5vcndheQ~~" },
	{ label: "Norwegian literature", setSpec: "TENDOk5vcndlZ2lhbiBsaXRlcmF0dXJl" },
	{ label: "Nuclear and particle physics. Atomic energy. Radioactivity", setSpec: "TENDOk51Y2xlYXIgYW5kIHBhcnRpY2xlIHBoeXNpY3MuIEF0b21pYyBlbmVyZ3kuIFJhZGlvYWN0aXZpdHk~" },
	{ label: "Nuclear engineering. Atomic power", setSpec: "TENDOk51Y2xlYXIgZW5naW5lZXJpbmcuIEF0b21pYyBwb3dlcg~~" },
	{ label: "Nursing", setSpec: "TENDOk51cnNpbmc~" },
	{ label: "Nutrition. Foods and food supply", setSpec: "TENDOk51dHJpdGlvbi4gRm9vZHMgYW5kIGZvb2Qgc3VwcGx5" },
	{ label: "Nutritional diseases. Deficiency diseases", setSpec: "TENDOk51dHJpdGlvbmFsIGRpc2Vhc2VzLiBEZWZpY2llbmN5IGRpc2Vhc2Vz" },
	{ label: "Ocean engineering", setSpec: "TENDOk9jZWFuIGVuZ2luZWVyaW5n" },
	{ label: "Oceanography", setSpec: "TENDOk9jZWFub2dyYXBoeQ~~" },
	{ label: "Office management", setSpec: "TENDOk9mZmljZSBtYW5hZ2VtZW50" },
	{ label: "Oils, fats, and waxes", setSpec: "TENDOk9pbHMsIGZhdHMsIGFuZCB3YXhlcw~~" },
	{ label: "Old Testament", setSpec: "TENDOk9sZCBUZXN0YW1lbnQ~" },
	{ label: "Ontology", setSpec: "TENDOk9udG9sb2d5" },
	{ label: "Ophthalmology", setSpec: "TENDOk9waHRoYWxtb2xvZ3k~" },
	{ label: "Optics. Light", setSpec: "TENDOk9wdGljcy4gTGlnaHQ~" },
	{ label: "Oral communication. Speech", setSpec: "TENDOk9yYWwgY29tbXVuaWNhdGlvbi4gU3BlZWNo" },
	{ label: "Oratory. Elocution, etc.", setSpec: "TENDOk9yYXRvcnkuIEVsb2N1dGlvbiwgZXRjLg~~" },
	{ label: "Organic chemistry", setSpec: "TENDOk9yZ2FuaWMgY2hlbWlzdHJ5" },
	{ label: "Organizational behaviour, change and effectiveness. Corporate culture", setSpec: "TENDOk9yZ2FuaXphdGlvbmFsIGJlaGF2aW91ciwgY2hhbmdlIGFuZCBlZmZlY3RpdmVuZXNzLiBDb3Jwb3JhdGUgY3VsdHVyZQ~~" },
	{ label: "Oriental languages and literatures", setSpec: "TENDOk9yaWVudGFsIGxhbmd1YWdlcyBhbmQgbGl0ZXJhdHVyZXM~" },
	{ label: "Orthopedic surgery", setSpec: "TENDOk9ydGhvcGVkaWMgc3VyZ2VyeQ~~" },
	{ label: "Osteopathy", setSpec: "TENDOk9zdGVvcGF0aHk~" },
	{ label: "Other Finnic languages and dialects", setSpec: "TENDOk90aGVyIEZpbm5pYyBsYW5ndWFnZXMgYW5kIGRpYWxlY3Rz" },
	{ label: "Other systems of medicine", setSpec: "TENDOk90aGVyIHN5c3RlbXMgb2YgbWVkaWNpbmU~" },
	{ label: "Otorhinolaryngology", setSpec: "TENDOk90b3JoaW5vbGFyeW5nb2xvZ3k~" },
	{ label: "Packaging", setSpec: "TENDOlBhY2thZ2luZw~~" },
	{ label: "Paints, pigments, varnishes, etc.", setSpec: "TENDOlBhaW50cywgcGlnbWVudHMsIHZhcm5pc2hlcywgZXRjLg~~" },
	{ label: "Paleontology", setSpec: "TENDOlBhbGVvbnRvbG9neQ~~" },
	{ label: "Pathology", setSpec: "TENDOlBhdGhvbG9neQ~~" },
	{ label: "Pediatrics", setSpec: "TENDOlBlZGlhdHJpY3M~" },
	{ label: "Periodicals", setSpec: "TENDOlBlcmlvZGljYWxz" },
	{ label: "Personnel management. Employment management", setSpec: "TENDOlBlcnNvbm5lbCBtYW5hZ2VtZW50LiBFbXBsb3ltZW50IG1hbmFnZW1lbnQ~" },
	{ label: "Petroleum refining. Petroleum products", setSpec: "TENDOlBldHJvbGV1bSByZWZpbmluZy4gUGV0cm9sZXVtIHByb2R1Y3Rz" },
	{ label: "Petrology", setSpec: "TENDOlBldHJvbG9neQ~~" },
	{ label: "Pharmaceutical industry", setSpec: "TENDOlBoYXJtYWNldXRpY2FsIGluZHVzdHJ5" },
	{ label: "Pharmacy and materia medica", setSpec: "TENDOlBoYXJtYWN5IGFuZCBtYXRlcmlhIG1lZGljYQ~~" },
	{ label: "Philology. Linguistics", setSpec: "TENDOlBoaWxvbG9neS4gTGluZ3Vpc3RpY3M~" },
	{ label: "Philosophy (General)", setSpec: "TENDOlBoaWxvc29waHkgKEdlbmVyYWwp" },
	{ label: "Philosophy of religion. Psychology of religion. Religion in relation to other subjects", setSpec: "TENDOlBoaWxvc29waHkgb2YgcmVsaWdpb24uIFBzeWNob2xvZ3kgb2YgcmVsaWdpb24uIFJlbGlnaW9uIGluIHJlbGF0aW9uIHRvIG90aGVyIHN1YmplY3Rz" },
	{ label: "Philosophy. Psychology. Religion", setSpec: "TENDOlBoaWxvc29waHkuIFBzeWNob2xvZ3kuIFJlbGlnaW9u" },
	{ label: "Photography", setSpec: "TENDOlBob3RvZ3JhcGh5" },
	{ label: "Physical and theoretical chemistry", setSpec: "TENDOlBoeXNpY2FsIGFuZCB0aGVvcmV0aWNhbCBjaGVtaXN0cnk~" },
	{ label: "Physical anthropology. Somatology", setSpec: "TENDOlBoeXNpY2FsIGFudGhyb3BvbG9neS4gU29tYXRvbG9neQ~~" },
	{ label: "Physical geography", setSpec: "TENDOlBoeXNpY2FsIGdlb2dyYXBoeQ~~" },
	{ label: "Physics", setSpec: "TENDOlBoeXNpY3M~" },
	{ label: "Physiology", setSpec: "TENDOlBoeXNpb2xvZ3k~" },
	{ label: "Plant culture", setSpec: "TENDOlBsYW50IGN1bHR1cmU~" },
	{ label: "Plant ecology", setSpec: "TENDOlBsYW50IGVjb2xvZ3k~" },
	{ label: "Plasma engineering. Applied plasma dynamics", setSpec: "TENDOlBsYXNtYSBlbmdpbmVlcmluZy4gQXBwbGllZCBwbGFzbWEgZHluYW1pY3M~" },
	{ label: "Plasma physics. Ionized gases", setSpec: "TENDOlBsYXNtYSBwaHlzaWNzLiBJb25pemVkIGdhc2Vz" },
	{ label: "Political institutions and public administration (General)", setSpec: "TENDOlBvbGl0aWNhbCBpbnN0aXR1dGlvbnMgYW5kIHB1YmxpYyBhZG1pbmlzdHJhdGlvbiAoR2VuZXJhbCk~" },
	{ label: "Political institutions and public administration - Asia (Asian studies only)", setSpec: "TENDOlBvbGl0aWNhbCBpbnN0aXR1dGlvbnMgYW5kIHB1YmxpYyBhZG1pbmlzdHJhdGlvbiAtIEFzaWEgKEFzaWFuIHN0dWRpZXMgb25seSk~" },
	{ label: "Political science", setSpec: "TENDOlBvbGl0aWNhbCBzY2llbmNl" },
	{ label: "Political science (General)", setSpec: "TENDOlBvbGl0aWNhbCBzY2llbmNlIChHZW5lcmFsKQ~~" },
	{ label: "Political theory", setSpec: "TENDOlBvbGl0aWNhbCB0aGVvcnk~" },
	{ label: "Polymers and polymer manufacture", setSpec: "TENDOlBvbHltZXJzIGFuZCBwb2x5bWVyIG1hbnVmYWN0dXJl" },
	{ label: "Practical Theology", setSpec: "TENDOlByYWN0aWNhbCBUaGVvbG9neQ~~" },
	{ label: "Practical religion. The Christian life", setSpec: "TENDOlByYWN0aWNhbCByZWxpZ2lvbi4gVGhlIENocmlzdGlhbiBsaWZl" },
	{ label: "Prehistoric archaeology", setSpec: "TENDOlByZWhpc3RvcmljIGFyY2hhZW9sb2d5" },
	{ label: "Print media", setSpec: "TENDOlByaW50IG1lZGlh" },
	{ label: "Printmaking and engraving", setSpec: "TENDOlByaW50bWFraW5nIGFuZCBlbmdyYXZpbmc~" },
	{ label: "Private international law. Conflict of laws", setSpec: "TENDOlByaXZhdGUgaW50ZXJuYXRpb25hbCBsYXcuIENvbmZsaWN0IG9mIGxhd3M~" },
	{ label: "Probabilities. Mathematical statistics", setSpec: "TENDOlByb2JhYmlsaXRpZXMuIE1hdGhlbWF0aWNhbCBzdGF0aXN0aWNz" },
	{ label: "Production capacity. Manufacturing capacity", setSpec: "TENDOlByb2R1Y3Rpb24gY2FwYWNpdHkuIE1hbnVmYWN0dXJpbmcgY2FwYWNpdHk~" },
	{ label: "Production management. Operations management", setSpec: "TENDOlByb2R1Y3Rpb24gbWFuYWdlbWVudC4gT3BlcmF0aW9ucyBtYW5hZ2VtZW50" },
	{ label: "Production of electric energy or power. Powerplants. Central stations", setSpec: "TENDOlByb2R1Y3Rpb24gb2YgZWxlY3RyaWMgZW5lcmd5IG9yIHBvd2VyLiBQb3dlcnBsYW50cy4gQ2VudHJhbCBzdGF0aW9ucw~~" },
	{ label: "Professions (General). Professional employees", setSpec: "TENDOlByb2Zlc3Npb25zIChHZW5lcmFsKS4gUHJvZmVzc2lvbmFsIGVtcGxveWVlcw~~" },
	{ label: "Property", setSpec: "TENDOlByb3BlcnR5" },
	{ label: "Protection of buildings. Including protection from dampness, fire, burglary", setSpec: "TENDOlByb3RlY3Rpb24gb2YgYnVpbGRpbmdzLiBJbmNsdWRpbmcgcHJvdGVjdGlvbiBmcm9tIGRhbXBuZXNzLCBmaXJlLCBidXJnbGFyeQ~~" },
	{ label: "Psychiatry", setSpec: "TENDOlBzeWNoaWF0cnk~" },
	{ label: "Psychology", setSpec: "TENDOlBzeWNob2xvZ3k~" },
	{ label: "Public aspects of medicine", setSpec: "TENDOlB1YmxpYyBhc3BlY3RzIG9mIG1lZGljaW5l" },
	{ label: "Public finance", setSpec: "TENDOlB1YmxpYyBmaW5hbmNl" },
	{ label: "Public law", setSpec: "TENDOlB1YmxpYyBsYXc~" },
	{ label: "Public relations. Industrial publicity", setSpec: "TENDOlB1YmxpYyByZWxhdGlvbnMuIEluZHVzdHJpYWwgcHVibGljaXR5" },
	{ label: "Purchasing. Selling. Sales personnel. Sales executives", setSpec: "TENDOlB1cmNoYXNpbmcuIFNlbGxpbmcuIFNhbGVzIHBlcnNvbm5lbC4gU2FsZXMgZXhlY3V0aXZlcw~~" },
	{ label: "Radioactivity and radioactive substances", setSpec: "TENDOlJhZGlvYWN0aXZpdHkgYW5kIHJhZGlvYWN0aXZlIHN1YnN0YW5jZXM~" },
	{ label: "Railroad engineering and operation", setSpec: "TENDOlJhaWxyb2FkIGVuZ2luZWVyaW5nIGFuZCBvcGVyYXRpb24~" },
	{ label: "Real estate business", setSpec: "TENDOlJlYWwgZXN0YXRlIGJ1c2luZXNz" },
	{ label: "Recreation leadership. Administration of recreation services", setSpec: "TENDOlJlY3JlYXRpb24gbGVhZGVyc2hpcC4gQWRtaW5pc3RyYXRpb24gb2YgcmVjcmVhdGlvbiBzZXJ2aWNlcw~~" },
	{ label: "Recreation. Leisure", setSpec: "TENDOlJlY3JlYXRpb24uIExlaXN1cmU~" },
	{ label: "Regional economics. Space in economics", setSpec: "TENDOlJlZ2lvbmFsIGVjb25vbWljcy4gU3BhY2UgaW4gZWNvbm9taWNz" },
	{ label: "Regional planning", setSpec: "TENDOlJlZ2lvbmFsIHBsYW5uaW5n" },
	{ label: "Regulation of industry, trade, and commerce. Occupational law", setSpec: "TENDOlJlZ3VsYXRpb24gb2YgaW5kdXN0cnksIHRyYWRlLCBhbmQgY29tbWVyY2UuIE9jY3VwYXRpb25hbCBsYXc~" },
	{ label: "Religion (General)", setSpec: "TENDOlJlbGlnaW9uIChHZW5lcmFsKQ~~" },
	{ label: "Religions of the world", setSpec: "TENDOlJlbGlnaW9ucyBvZiB0aGUgd29ybGQ~" },
	{ label: "Religions. Mythology. Rationalism", setSpec: "TENDOlJlbGlnaW9ucy4gTXl0aG9sb2d5LiBSYXRpb25hbGlzbQ~~" },
	{ label: "Religious ethics", setSpec: "TENDOlJlbGlnaW91cyBldGhpY3M~" },
	{ label: "Renewable energy sources", setSpec: "TENDOlJlbmV3YWJsZSBlbmVyZ3kgc291cmNlcw~~" },
	{ label: "Reproduction", setSpec: "TENDOlJlcHJvZHVjdGlvbg~~" },
	{ label: "Revenue. Taxation. Internal revenue", setSpec: "TENDOlJldmVudWUuIFRheGF0aW9uLiBJbnRlcm5hbCByZXZlbnVl" },
	{ label: "Risk in industry. Risk management", setSpec: "TENDOlJpc2sgaW4gaW5kdXN0cnkuIFJpc2sgbWFuYWdlbWVudA~~" },
	{ label: "River protective works. Regulation. Flood control", setSpec: "TENDOlJpdmVyIHByb3RlY3RpdmUgd29ya3MuIFJlZ3VsYXRpb24uIEZsb29kIGNvbnRyb2w~" },
	{ label: "River, lake, and water-supply engineering (General)", setSpec: "TENDOlJpdmVyLCBsYWtlLCBhbmQgd2F0ZXItc3VwcGx5IGVuZ2luZWVyaW5nIChHZW5lcmFsKQ~~" },
	{ label: "Romanic languages", setSpec: "TENDOlJvbWFuaWMgbGFuZ3VhZ2Vz" },
	{ label: "Rural and farm sanitary engineering", setSpec: "TENDOlJ1cmFsIGFuZCBmYXJtIHNhbml0YXJ5IGVuZ2luZWVyaW5n" },
	{ label: "Rural industries", setSpec: "TENDOlJ1cmFsIGluZHVzdHJpZXM~" },
	{ label: "Science", setSpec: "TENDOlNjaWVuY2U~" },
	{ label: "Science (General)", setSpec: "TENDOlNjaWVuY2UgKEdlbmVyYWwp" },
	{ label: "Sculpture", setSpec: "TENDOlNjdWxwdHVyZQ~~" },
	{ label: "Semantics", setSpec: "TENDOlNlbWFudGljcw~~" },
	{ label: "Settlements", setSpec: "TENDOlNldHRsZW1lbnRz" },
	{ label: "Sewage collection and disposal systems. Sewerage", setSpec: "TENDOlNld2FnZSBjb2xsZWN0aW9uIGFuZCBkaXNwb3NhbCBzeXN0ZW1zLiBTZXdlcmFnZQ~~" },
	{ label: "Shipment of goods. Delivery of goods", setSpec: "TENDOlNoaXBtZW50IG9mIGdvb2RzLiBEZWxpdmVyeSBvZiBnb29kcw~~" },
	{ label: "Slavic languages. Baltic languages. Albanian languages", setSpec: "TENDOlNsYXZpYyBsYW5ndWFnZXMuIEJhbHRpYyBsYW5ndWFnZXMuIEFsYmFuaWFuIGxhbmd1YWdlcw~~" },
	{ label: "Small and medium-sized businesses, artisans, handicrafts, trades", setSpec: "TENDOlNtYWxsIGFuZCBtZWRpdW0tc2l6ZWQgYnVzaW5lc3NlcywgYXJ0aXNhbnMsIGhhbmRpY3JhZnRzLCB0cmFkZXM~" },
	{ label: "Social Sciences", setSpec: "TENDOlNvY2lhbCBTY2llbmNlcw~~" },
	{ label: "Social history and conditions. Social problems. Social reform", setSpec: "TENDOlNvY2lhbCBoaXN0b3J5IGFuZCBjb25kaXRpb25zLiBTb2NpYWwgcHJvYmxlbXMuIFNvY2lhbCByZWZvcm0~" },
	{ label: "Social insurance. Social security. Pension", setSpec: "TENDOlNvY2lhbCBpbnN1cmFuY2UuIFNvY2lhbCBzZWN1cml0eS4gUGVuc2lvbg~~" },
	{ label: "Social legislation", setSpec: "TENDOlNvY2lhbCBsZWdpc2xhdGlvbg~~" },
	{ label: "Social pathology. Social and public welfare. Criminology", setSpec: "TENDOlNvY2lhbCBwYXRob2xvZ3kuIFNvY2lhbCBhbmQgcHVibGljIHdlbGZhcmUuIENyaW1pbm9sb2d5" },
	{ label: "Social responsibility of business", setSpec: "TENDOlNvY2lhbCByZXNwb25zaWJpbGl0eSBvZiBidXNpbmVzcw~~" },
	{ label: "Social sciences (General)", setSpec: "TENDOlNvY2lhbCBzY2llbmNlcyAoR2VuZXJhbCk~" },
	{ label: "Social sciences and state - Asia (Asian studies only)", setSpec: "TENDOlNvY2lhbCBzY2llbmNlcyBhbmQgc3RhdGUgLSBBc2lhIChBc2lhbiBzdHVkaWVzIG9ubHkp" },
	{ label: "Socialism. Communism. Anarchism", setSpec: "TENDOlNvY2lhbGlzbS4gQ29tbXVuaXNtLiBBbmFyY2hpc20~" },
	{ label: "Societies: secret, benevolent, etc.", setSpec: "TENDOlNvY2lldGllczogc2VjcmV0LCBiZW5ldm9sZW50LCBldGMu" },
	{ label: "Sociology (General)", setSpec: "TENDOlNvY2lvbG9neSAoR2VuZXJhbCk~" },
	{ label: "South Asia. Southeast Asia. East Asia", setSpec: "TENDOlNvdXRoIEFzaWEuIFNvdXRoZWFzdCBBc2lhLiBFYXN0IEFzaWE~" },
	{ label: "Special aspects of education", setSpec: "TENDOlNwZWNpYWwgYXNwZWN0cyBvZiBlZHVjYXRpb24~" },
	{ label: "Special industries and trades", setSpec: "TENDOlNwZWNpYWwgaW5kdXN0cmllcyBhbmQgdHJhZGVz" },
	{ label: "Special situations and conditions", setSpec: "TENDOlNwZWNpYWwgc2l0dWF0aW9ucyBhbmQgY29uZGl0aW9ucw~~" },
	{ label: "Special types of environment", setSpec: "TENDOlNwZWNpYWwgdHlwZXMgb2YgZW52aXJvbm1lbnQ~" },
	{ label: "Specialties of internal medicine", setSpec: "TENDOlNwZWNpYWx0aWVzIG9mIGludGVybmFsIG1lZGljaW5l" },
	{ label: "Speculative philosophy", setSpec: "TENDOlNwZWN1bGF0aXZlIHBoaWxvc29waHk~" },
	{ label: "Sports", setSpec: "TENDOlNwb3J0cw~~" },
	{ label: "Sports medicine", setSpec: "TENDOlNwb3J0cyBtZWRpY2luZQ~~" },
	{ label: "Standardization. Simplification. Waste", setSpec: "TENDOlN0YW5kYXJkaXphdGlvbi4gU2ltcGxpZmljYXRpb24uIFdhc3Rl" },
	{ label: "Statistics", setSpec: "TENDOlN0YXRpc3RpY3M~" },
	{ label: "Stratigraphy", setSpec: "TENDOlN0cmF0aWdyYXBoeQ~~" },
	{ label: "Structural engineering (General)", setSpec: "TENDOlN0cnVjdHVyYWwgZW5naW5lZXJpbmcgKEdlbmVyYWwp" },
	{ label: "Style. Composition. Rhetoric", setSpec: "TENDOlN0eWxlLiBDb21wb3NpdGlvbi4gUmhldG9yaWM~" },
	{ label: "Suburban cities and towns", setSpec: "TENDOlN1YnVyYmFuIGNpdGllcyBhbmQgdG93bnM~" },
	{ label: "Surgery", setSpec: "TENDOlN1cmdlcnk~" },
	{ label: "Surveying", setSpec: "TENDOlN1cnZleWluZw~~" },
	{ label: "Surveys (General)", setSpec: "TENDOlN1cnZleXMgKEdlbmVyYWwp" },
	{ label: "Systems engineering", setSpec: "TENDOlN5c3RlbXMgZW5naW5lZXJpbmc~" },
	{ label: "Systems of building construction. Including fireproof construction, concrete construction", setSpec: "TENDOlN5c3RlbXMgb2YgYnVpbGRpbmcgY29uc3RydWN0aW9uLiBJbmNsdWRpbmcgZmlyZXByb29mIGNvbnN0cnVjdGlvbiwgY29uY3JldGUgY29uc3RydWN0aW9u" },
	{ label: "Technical hydraulics", setSpec: "TENDOlRlY2huaWNhbCBoeWRyYXVsaWNz" },
	{ label: "Technological innovations. Automation", setSpec: "TENDOlRlY2hub2xvZ2ljYWwgaW5ub3ZhdGlvbnMuIEF1dG9tYXRpb24~" },
	{ label: "Technology", setSpec: "TENDOlRlY2hub2xvZ3k~" },
	{ label: "Technology (General)", setSpec: "TENDOlRlY2hub2xvZ3kgKEdlbmVyYWwp" },
	{ label: "Telecommunication", setSpec: "TENDOlRlbGVjb21tdW5pY2F0aW9u" },
	{ label: "Textile bleaching, dyeing, printing, etc.", setSpec: "TENDOlRleHRpbGUgYmxlYWNoaW5nLCBkeWVpbmcsIHByaW50aW5nLCBldGMu" },
	{ label: "The Bible", setSpec: "TENDOlRoZSBCaWJsZQ~~" },
	{ label: "The city as an economic factor. City promotion", setSpec: "TENDOlRoZSBjaXR5IGFzIGFuIGVjb25vbWljIGZhY3Rvci4gQ2l0eSBwcm9tb3Rpb24~" },
	{ label: "The family. Marriage. Woman", setSpec: "TENDOlRoZSBmYW1pbHkuIE1hcnJpYWdlLiBXb21hbg~~" },
	{ label: "The performing arts. Show business", setSpec: "TENDOlRoZSBwZXJmb3JtaW5nIGFydHMuIFNob3cgYnVzaW5lc3M~" },
	{ label: "Theory and practice of education", setSpec: "TENDOlRoZW9yeSBhbmQgcHJhY3RpY2Ugb2YgZWR1Y2F0aW9u" },
	{ label: "Therapeutics. Pharmacology", setSpec: "TENDOlRoZXJhcGV1dGljcy4gUGhhcm1hY29sb2d5" },
	{ label: "Therapeutics. Psychotherapy", setSpec: "TENDOlRoZXJhcGV1dGljcy4gUHN5Y2hvdGhlcmFweQ~~" },
	{ label: "Thermodynamics", setSpec: "TENDOlRoZXJtb2R5bmFtaWNz" },
	{ label: "Toxicology. Poisons", setSpec: "TENDOlRveGljb2xvZ3kuIFBvaXNvbnM~" },
	{ label: "Trade associations", setSpec: "TENDOlRyYWRlIGFzc29jaWF0aW9ucw~~" },
	{ label: "Translating and interpreting", setSpec: "TENDOlRyYW5zbGF0aW5nIGFuZCBpbnRlcnByZXRpbmc~" },
	{ label: "Transportation and communication", setSpec: "TENDOlRyYW5zcG9ydGF0aW9uIGFuZCBjb21tdW5pY2F0aW9u" },
	{ label: "Transportation and communications", setSpec: "TENDOlRyYW5zcG9ydGF0aW9uIGFuZCBjb21tdW5pY2F0aW9ucw~~" },
	{ label: "Transportation engineering", setSpec: "TENDOlRyYW5zcG9ydGF0aW9uIGVuZ2luZWVyaW5n" },
	{ label: "United States", setSpec: "TENDOlVuaXRlZCBTdGF0ZXM~" },
	{ label: "United States local history", setSpec: "TENDOlVuaXRlZCBTdGF0ZXMgbG9jYWwgaGlzdG9yeQ~~" },
	{ label: "Unlocalized maps (Asian studies only)", setSpec: "TENDOlVubG9jYWxpemVkIG1hcHMgKEFzaWFuIHN0dWRpZXMgb25seSk~" },
	{ label: "Ural-Altaic languages", setSpec: "TENDOlVyYWwtQWx0YWljIGxhbmd1YWdlcw~~" },
	{ label: "Urban groups. The city. Urban sociology", setSpec: "TENDOlVyYmFuIGdyb3Vwcy4gVGhlIGNpdHkuIFVyYmFuIHNvY2lvbG9neQ~~" },
	{ label: "Urban renewal. Urban redevelopment", setSpec: "TENDOlVyYmFuIHJlbmV3YWwuIFVyYmFuIHJlZGV2ZWxvcG1lbnQ~" },
	{ label: "Urbanization. City and country", setSpec: "TENDOlVyYmFuaXphdGlvbi4gQ2l0eSBhbmQgY291bnRyeQ~~" },
	{ label: "Veterinary medicine", setSpec: "TENDOlZldGVyaW5hcnkgbWVkaWNpbmU~" },
	{ label: "Visual arts", setSpec: "TENDOlZpc3VhbCBhcnRz" },
	{ label: "Vocational guidance. Career development", setSpec: "TENDOlZvY2F0aW9uYWwgZ3VpZGFuY2UuIENhcmVlciBkZXZlbG9wbWVudA~~" },
	{ label: "Vocational rehabilitation. Employment of people with disabilities", setSpec: "TENDOlZvY2F0aW9uYWwgcmVoYWJpbGl0YXRpb24uIEVtcGxveW1lbnQgb2YgcGVvcGxlIHdpdGggZGlzYWJpbGl0aWVz" },
	{ label: "Water supply for domestic and industrial purposes", setSpec: "TENDOldhdGVyIHN1cHBseSBmb3IgZG9tZXN0aWMgYW5kIGluZHVzdHJpYWwgcHVycG9zZXM~" },
	{ label: "Women. Feminism", setSpec: "TENDOldvbWVuLiBGZW1pbmlzbQ~~" },
	{ label: "Zoology", setSpec: "TENDOlpvb2xvZ3k~" },
];

/**
 * ArXiv top-level group/archive -> canonical FIELDS_OF_STUDY entry. Reuses
 * the existing search-facing prefix map (`fields.ts`) rather than
 * duplicating it — it's already keyed by the same archive prefixes
 * `groupCategories` in `sources/arxiv.ts` fans out on.
 */
export const ARXIV_GROUP_TO_CANONICAL: Record<string, FieldOfStudy> =
	ARXIV_PREFIX_TO_FIELD;

/**
 * DOAJ LCC term (label) -> canonical FIELDS_OF_STUDY entry. Only the terms
 * already implied by the pre-rewrite REST adapter's S2_TO_LCC map are
 * covered — full 538-term coverage is a separate, deferred curation task
 * (tech spec §9). Unmapped terms fall back to "Uncategorized".
 */
export const DOAJ_LCC_TO_CANONICAL: Record<string, FieldOfStudy> = {
	"Electronic computers. Computer science": "Computer Science",
	Mathematics: "Mathematics",
	Physics: "Physics",
	"Biology (General)": "Biology",
	Chemistry: "Chemistry",
	Medicine: "Medicine",
	"Engineering (General). Civil engineering (General)": "Engineering",
	"Economics as a science": "Economics",
	Psychology: "Psychology",
	"Sociology (General)": "Sociology",
	"History (General) and history of Europe": "History",
	"Philosophy (General)": "Philosophy",
	"Arts in general": "Art",
	"Political science (General)": "Political Science",
	"Geography (General)": "Geography",
	Geology: "Geology",
	"Environmental sciences": "Environmental Science",
	"Materials of engineering and construction. Mechanics of materials":
		"Materials Science",
	"Language. Linguistic theory. Comparative grammar": "Linguistics",
	"Education (General)": "Education",
	"Law in general. Comparative and uniform law. Jurisprudence": "Law",
	Business: "Business",
	"Agriculture (General)": "Agricultural and Food Sciences",
};
